version: '3.9'
services:
  flock:
    container_name: flock
    restart: always
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - flock
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 